#Mybatis
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml

logging:
  level:
    org.example.performancecache.mapper: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study_db
    username: root
    password: ${my.password}